const TitleConstants = {
	employeeId: "Employee Id",
	title: "Title",
	firstName: "First Name",
	lastName: "Last Name",
	emailAddress: "Email",
	alternateEmail: "Alternate Email",
	birthDateAndMonth: "Birthdate",
	corpId: " CORP Id",
	deskNumber: "Desk Number",
	extn: "Extension",
	mobile: "Mobile",
	additionalContact: "Additional Contact",
	city: "City",
	racfId: "RACF Id",
	roleName: "Role Name",
	scrumTeamName: "Scrum Team",
	active: "Active",
	createdDate: "Created Date",
	updatedDate: "Updated Date",
	address: "Address",
	id: "id",
	addressType: "Address Type",
	addressLine1: "Address Line 1",
	addressLine2: "Address Line 2",
	addressLine3: "Address Line 3",
	postCode: "Post Code",
	state: "State",
	country: "Country",
	groupId: "Group Id",
	team: "Team",
	supervisorId: "Supervisor Id",
	peerId: "Peer Id",
	projectTrackCode: "Project Track Code",
	scrumTeamId: "Scrum Team Id",
	isBillable: "Billable",
	designation: "Designation",
	designationEffectiveDate: "Effective Date",
	scrumMasterName: "Scrum Master",
	platformManagerName: "Platform Manager",
	trackName: "Track Name",
	firstSpoc: "First Spoc",
	scrumTeamCreatedDate: "Created Date",
	secondSpoc: "Second Spoc"
};

export default TitleConstants;
